/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait AccessPoliciesApi: Send + Sync {
    /// GET /organizations/{id}/access-policies/people/potential-grantees
    async fn get_people_potential_grantees<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PotentialGranteeResponseModelListResponseModel, Error>;

    /// GET /projects/{id}/access-policies/people
    async fn get_project_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ProjectPeopleAccessPoliciesResponseModel, Error>;

    /// GET /organizations/{id}/access-policies/projects/potential-grantees
    async fn get_project_potential_grantees<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PotentialGranteeResponseModelListResponseModel, Error>;

    /// GET /projects/{id}/access-policies/service-accounts
    async fn get_project_service_accounts_access_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ProjectServiceAccountsAccessPoliciesResponseModel, Error>;

    /// GET /secrets/{secretId}/access-policies
    async fn get_secret_access_policies<'a>(
        &self,
        secret_id: uuid::Uuid,
    ) -> Result<models::SecretAccessPoliciesResponseModel, Error>;

    /// GET /service-accounts/{id}/granted-policies
    async fn get_service_account_granted_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ServiceAccountGrantedPoliciesPermissionDetailsResponseModel, Error>;

    /// GET /service-accounts/{id}/access-policies/people
    async fn get_service_account_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ServiceAccountPeopleAccessPoliciesResponseModel, Error>;

    /// GET /organizations/{id}/access-policies/service-accounts/potential-grantees
    async fn get_service_accounts_potential_grantees<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PotentialGranteeResponseModelListResponseModel, Error>;

    /// PUT /projects/{id}/access-policies/people
    async fn put_project_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
        people_access_policies_request_model: Option<models::PeopleAccessPoliciesRequestModel>,
    ) -> Result<models::ProjectPeopleAccessPoliciesResponseModel, Error>;

    /// PUT /projects/{id}/access-policies/service-accounts
    async fn put_project_service_accounts_access_policies<'a>(
        &self,
        id: uuid::Uuid,
        project_service_accounts_access_policies_request_model: Option<
            models::ProjectServiceAccountsAccessPoliciesRequestModel,
        >,
    ) -> Result<models::ProjectServiceAccountsAccessPoliciesResponseModel, Error>;

    /// PUT /service-accounts/{id}/granted-policies
    async fn put_service_account_granted_policies<'a>(
        &self,
        id: uuid::Uuid,
        service_account_granted_policies_request_model: Option<
            models::ServiceAccountGrantedPoliciesRequestModel,
        >,
    ) -> Result<models::ServiceAccountGrantedPoliciesPermissionDetailsResponseModel, Error>;

    /// PUT /service-accounts/{id}/access-policies/people
    async fn put_service_account_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
        people_access_policies_request_model: Option<models::PeopleAccessPoliciesRequestModel>,
    ) -> Result<models::ServiceAccountPeopleAccessPoliciesResponseModel, Error>;
}

pub struct AccessPoliciesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl AccessPoliciesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl AccessPoliciesApi for AccessPoliciesApiClient {
    async fn get_people_potential_grantees<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PotentialGranteeResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{id}/access-policies/people/potential-grantees",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_project_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ProjectPeopleAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/projects/{id}/access-policies/people",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_project_potential_grantees<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PotentialGranteeResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{id}/access-policies/projects/potential-grantees",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_project_service_accounts_access_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ProjectServiceAccountsAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/projects/{id}/access-policies/service-accounts",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_secret_access_policies<'a>(
        &self,
        secret_id: uuid::Uuid,
    ) -> Result<models::SecretAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/secrets/{secretId}/access-policies",
            local_var_configuration.base_path,
            secretId = secret_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_service_account_granted_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ServiceAccountGrantedPoliciesPermissionDetailsResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/granted-policies",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_service_account_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ServiceAccountPeopleAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/access-policies/people",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_service_accounts_potential_grantees<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PotentialGranteeResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{id}/access-policies/service-accounts/potential-grantees",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn put_project_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
        people_access_policies_request_model: Option<models::PeopleAccessPoliciesRequestModel>,
    ) -> Result<models::ProjectPeopleAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/projects/{id}/access-policies/people",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&people_access_policies_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn put_project_service_accounts_access_policies<'a>(
        &self,
        id: uuid::Uuid,
        project_service_accounts_access_policies_request_model: Option<
            models::ProjectServiceAccountsAccessPoliciesRequestModel,
        >,
    ) -> Result<models::ProjectServiceAccountsAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/projects/{id}/access-policies/service-accounts",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&project_service_accounts_access_policies_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn put_service_account_granted_policies<'a>(
        &self,
        id: uuid::Uuid,
        service_account_granted_policies_request_model: Option<
            models::ServiceAccountGrantedPoliciesRequestModel,
        >,
    ) -> Result<models::ServiceAccountGrantedPoliciesPermissionDetailsResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/granted-policies",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&service_account_granted_policies_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn put_service_account_people_access_policies<'a>(
        &self,
        id: uuid::Uuid,
        people_access_policies_request_model: Option<models::PeopleAccessPoliciesRequestModel>,
    ) -> Result<models::ServiceAccountPeopleAccessPoliciesResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/access-policies/people",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&people_access_policies_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }
}
