/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait CipherLeaseApi: Send + Sync {
    /// POST /leases/ciphers/{id}
    async fn post<'a>(
        &self,
        id: uuid::Uuid,
        access_request_create_request_model: models::AccessRequestCreateRequestModel,
    ) -> Result<models::AccessRequestResultResponseModel, Error>;

    /// GET /leases/ciphers/{id}/pre-check
    async fn pre_check<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::AccessPreCheckResponseModel, Error>;

    /// GET /leases/ciphers/{id}/state
    async fn state<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::CipherAccessStateResponseModel, Error>;
}

pub struct CipherLeaseApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl CipherLeaseApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl CipherLeaseApi for CipherLeaseApiClient {
    async fn post<'a>(
        &self,
        id: uuid::Uuid,
        access_request_create_request_model: models::AccessRequestCreateRequestModel,
    ) -> Result<models::AccessRequestResultResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/leases/ciphers/{id}",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&access_request_create_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn pre_check<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::AccessPreCheckResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/leases/ciphers/{id}/pre-check",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn state<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::CipherAccessStateResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/leases/ciphers/{id}/state",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }
}
