/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait EmergencyAccessApi: Send + Sync {
    /// POST /emergency-access/{id}/accept
    async fn accept<'a>(
        &self,
        id: uuid::Uuid,
        organization_user_accept_request_model: Option<models::OrganizationUserAcceptRequestModel>,
    ) -> Result<(), Error>;

    /// POST /emergency-access/{id}/approve
    async fn approve<'a>(&self, id: uuid::Uuid) -> Result<(), Error>;

    /// POST /emergency-access/{id}/confirm
    async fn confirm<'a>(
        &self,
        id: uuid::Uuid,
        organization_user_confirm_request_model: Option<
            models::OrganizationUserConfirmRequestModel,
        >,
    ) -> Result<(), Error>;

    /// DELETE /emergency-access/{id}
    async fn delete<'a>(&self, id: uuid::Uuid) -> Result<(), Error>;

    /// GET /emergency-access/{id}
    async fn get<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::EmergencyAccessGranteeDetailsResponseModel, Error>;

    /// GET /emergency-access/{id}/{cipherId}/attachment/{attachmentId}
    async fn get_attachment_data<'a>(
        &self,
        id: uuid::Uuid,
        cipher_id: uuid::Uuid,
        attachment_id: &'a str,
    ) -> Result<models::AttachmentResponseModel, Error>;

    /// GET /emergency-access/trusted
    async fn get_contacts(
        &self,
    ) -> Result<models::EmergencyAccessGranteeDetailsResponseModelListResponseModel, Error>;

    /// GET /emergency-access/granted
    async fn get_grantees(
        &self,
    ) -> Result<models::EmergencyAccessGrantorDetailsResponseModelListResponseModel, Error>;

    /// POST /emergency-access/{id}/initiate
    async fn initiate<'a>(&self, id: uuid::Uuid) -> Result<(), Error>;

    /// POST /emergency-access/invite
    async fn invite<'a>(
        &self,
        emergency_access_invite_request_model: Option<models::EmergencyAccessInviteRequestModel>,
    ) -> Result<(), Error>;

    /// POST /emergency-access/{id}/password
    async fn password<'a>(
        &self,
        id: uuid::Uuid,
        emergency_access_password_request_model: Option<
            models::EmergencyAccessPasswordRequestModel,
        >,
    ) -> Result<(), Error>;

    /// GET /emergency-access/{id}/policies
    async fn policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PolicyResponseModelListResponseModel, Error>;

    /// PUT /emergency-access/{id}
    async fn put<'a>(
        &self,
        id: uuid::Uuid,
        emergency_access_update_request_model: Option<models::EmergencyAccessUpdateRequestModel>,
    ) -> Result<(), Error>;

    /// POST /emergency-access/{id}/reinvite
    async fn reinvite<'a>(&self, id: uuid::Uuid) -> Result<(), Error>;

    /// POST /emergency-access/{id}/reject
    async fn reject<'a>(&self, id: uuid::Uuid) -> Result<(), Error>;

    /// POST /emergency-access/{id}/takeover
    async fn takeover<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::EmergencyAccessTakeoverResponseModel, Error>;

    /// POST /emergency-access/{id}/view
    async fn view_ciphers<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::EmergencyAccessViewResponseModel, Error>;
}

pub struct EmergencyAccessApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl EmergencyAccessApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl EmergencyAccessApi for EmergencyAccessApiClient {
    async fn accept<'a>(
        &self,
        id: uuid::Uuid,
        organization_user_accept_request_model: Option<models::OrganizationUserAcceptRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/accept",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&organization_user_accept_request_model);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn approve<'a>(&self, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/approve",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn confirm<'a>(
        &self,
        id: uuid::Uuid,
        organization_user_confirm_request_model: Option<
            models::OrganizationUserConfirmRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/confirm",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_confirm_request_model);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn delete<'a>(&self, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn get<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::EmergencyAccessGranteeDetailsResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::EmergencyAccessGranteeDetailsResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::EmergencyAccessGranteeDetailsResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn get_attachment_data<'a>(
        &self,
        id: uuid::Uuid,
        cipher_id: uuid::Uuid,
        attachment_id: &'a str,
    ) -> Result<models::AttachmentResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/{cipherId}/attachment/{attachmentId}",
            local_var_configuration.base_path,
            id = id,
            cipherId = cipher_id,
            attachmentId = crate::apis::urlencode(attachment_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AttachmentResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AttachmentResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn get_contacts(
        &self,
    ) -> Result<models::EmergencyAccessGranteeDetailsResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/trusted",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::EmergencyAccessGranteeDetailsResponseModelListResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::EmergencyAccessGranteeDetailsResponseModelListResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn get_grantees(
        &self,
    ) -> Result<models::EmergencyAccessGrantorDetailsResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/granted",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::EmergencyAccessGrantorDetailsResponseModelListResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::EmergencyAccessGrantorDetailsResponseModelListResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn initiate<'a>(&self, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/initiate",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn invite<'a>(
        &self,
        emergency_access_invite_request_model: Option<models::EmergencyAccessInviteRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/invite",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&emergency_access_invite_request_model);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn password<'a>(
        &self,
        id: uuid::Uuid,
        emergency_access_password_request_model: Option<
            models::EmergencyAccessPasswordRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/password",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&emergency_access_password_request_model);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn policies<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::PolicyResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/policies",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::PolicyResponseModelListResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PolicyResponseModelListResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn put<'a>(
        &self,
        id: uuid::Uuid,
        emergency_access_update_request_model: Option<models::EmergencyAccessUpdateRequestModel>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&emergency_access_update_request_model);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn reinvite<'a>(&self, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/reinvite",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn reject<'a>(&self, id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/reject",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn takeover<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::EmergencyAccessTakeoverResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/takeover",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::EmergencyAccessTakeoverResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::EmergencyAccessTakeoverResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn view_ciphers<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::EmergencyAccessViewResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/emergency-access/{id}/view",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::EmergencyAccessViewResponseModel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::EmergencyAccessViewResponseModel`"
                    ))));
                }
            }
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }
}
