/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait OrganizationUsersKeysApi: Send + Sync {
    /// GET /organizations/{orgId}/users/keys/pending-v2-upgrades
    async fn get_pending_v2_upgrades<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationUserPendingV2UpgradeResponseModelListResponseModel, Error>;

    /// POST /organizations/{orgId}/users/keys/v2-upgrades
    /// Every membership is written, or none of them are.
    async fn post_v2_upgrades<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_v2_upgrades_request_model: Option<
            models::OrganizationUserV2UpgradesRequestModel,
        >,
    ) -> Result<(), Error>;
}

pub struct OrganizationUsersKeysApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationUsersKeysApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl OrganizationUsersKeysApi for OrganizationUsersKeysApiClient {
    async fn get_pending_v2_upgrades<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationUserPendingV2UpgradeResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/keys/pending-v2-upgrades",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    /// Every membership is written, or none of them are.
    async fn post_v2_upgrades<'a>(
        &self,
        org_id: uuid::Uuid,
        organization_user_v2_upgrades_request_model: Option<
            models::OrganizationUserV2UpgradesRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{orgId}/users/keys/v2-upgrades",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_user_v2_upgrades_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }
}
