/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait OrganizationIntegrationConfigurationApi: Send + Sync {
    /// POST /organizations/{organizationId}/integrations/{integrationId}/configurations
    async fn create<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
        organization_integration_configuration_request_model: Option<
            models::OrganizationIntegrationConfigurationRequestModel,
        >,
    ) -> Result<models::OrganizationIntegrationConfigurationResponseModel, Error<CreateError>>;

    /// DELETE /organizations/{organizationId}/integrations/{integrationId}/configurations/
    /// {configurationId}
    async fn delete<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
        configuration_id: uuid::Uuid,
    ) -> Result<(), Error<DeleteError>>;

    /// GET /organizations/{organizationId}/integrations/{integrationId}/configurations
    async fn get<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
    ) -> Result<Vec<models::OrganizationIntegrationConfigurationResponseModel>, Error<GetError>>;

    /// PUT /organizations/{organizationId}/integrations/{integrationId}/configurations/
    /// {configurationId}
    async fn update<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
        configuration_id: uuid::Uuid,
        organization_integration_configuration_request_model: Option<
            models::OrganizationIntegrationConfigurationRequestModel,
        >,
    ) -> Result<models::OrganizationIntegrationConfigurationResponseModel, Error<UpdateError>>;
}

pub struct OrganizationIntegrationConfigurationApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationIntegrationConfigurationApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl OrganizationIntegrationConfigurationApi for OrganizationIntegrationConfigurationApiClient {
    async fn create<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
        organization_integration_configuration_request_model: Option<
            models::OrganizationIntegrationConfigurationRequestModel,
        >,
    ) -> Result<models::OrganizationIntegrationConfigurationResponseModel, Error<CreateError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/integrations/{integrationId}/configurations",
            local_var_configuration.base_path,
            organizationId = organization_id,
            integrationId = integration_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_integration_configuration_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn delete<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
        configuration_id: uuid::Uuid,
    ) -> Result<(), Error<DeleteError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/integrations/{integrationId}/configurations/{configurationId}",
            local_var_configuration.base_path,
            organizationId = organization_id,
            integrationId = integration_id,
            configurationId = configuration_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
    ) -> Result<Vec<models::OrganizationIntegrationConfigurationResponseModel>, Error<GetError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/integrations/{integrationId}/configurations",
            local_var_configuration.base_path,
            organizationId = organization_id,
            integrationId = integration_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn update<'a>(
        &self,
        organization_id: uuid::Uuid,
        integration_id: uuid::Uuid,
        configuration_id: uuid::Uuid,
        organization_integration_configuration_request_model: Option<
            models::OrganizationIntegrationConfigurationRequestModel,
        >,
    ) -> Result<models::OrganizationIntegrationConfigurationResponseModel, Error<UpdateError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/integrations/{integrationId}/configurations/{configurationId}",
            local_var_configuration.base_path,
            organizationId = organization_id,
            integrationId = integration_id,
            configurationId = configuration_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_integration_configuration_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }
}

/// struct for typed errors of method [`OrganizationIntegrationConfigurationApi::create`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateError {
    UnknownValue(serde_json::Value),
}
/// struct for typed errors of method [`OrganizationIntegrationConfigurationApi::delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteError {
    UnknownValue(serde_json::Value),
}
/// struct for typed errors of method [`OrganizationIntegrationConfigurationApi::get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetError {
    UnknownValue(serde_json::Value),
}
/// struct for typed errors of method [`OrganizationIntegrationConfigurationApi::update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateError {
    UnknownValue(serde_json::Value),
}
