/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait ProviderBillingApi: Send + Sync {
    /// GET /providers/{providerId}/billing/invoices/{invoiceId}
    async fn generate_client_invoice_report<'a>(
        &self,
        provider_id: uuid::Uuid,
        invoice_id: &'a str,
    ) -> Result<(), Error>;

    /// GET /providers/{providerId}/billing/invoices
    async fn get_invoices<'a>(&self, provider_id: uuid::Uuid) -> Result<(), Error>;

    /// GET /providers/{providerId}/billing/subscription
    async fn get_subscription<'a>(&self, provider_id: uuid::Uuid) -> Result<(), Error>;
}

pub struct ProviderBillingApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ProviderBillingApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl ProviderBillingApi for ProviderBillingApiClient {
    async fn generate_client_invoice_report<'a>(
        &self,
        provider_id: uuid::Uuid,
        invoice_id: &'a str,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/providers/{providerId}/billing/invoices/{invoiceId}",
            local_var_configuration.base_path,
            providerId = provider_id,
            invoiceId = crate::apis::urlencode(invoice_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn get_invoices<'a>(&self, provider_id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/providers/{providerId}/billing/invoices",
            local_var_configuration.base_path,
            providerId = provider_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }

    async fn get_subscription<'a>(&self, provider_id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/providers/{providerId}/billing/subscription",
            local_var_configuration.base_path,
            providerId = provider_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        let local_var_resp = local_var_req_builder.send().await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            Err(Error::Response {
                status: local_var_status,
                content: local_var_content,
            })
        }
    }
}
