/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait SelfHostedOrganizationSponsorshipsApi: Send + Sync {
    /// DELETE /organization/sponsorship/self-hosted/{organizationId}/{sponsoredFriendlyName}/revoke
    async fn admin_initiated_revoke_sponsorship<'a>(
        &self,
        organization_id: uuid::Uuid,
        sponsored_friendly_name: &'a str,
    ) -> Result<(), Error>;

    /// POST /organization/sponsorship/self-hosted/{sponsoringOrgId}/families-for-enterprise
    async fn create_sponsorship<'a>(
        &self,
        sponsoring_org_id: uuid::Uuid,
        organization_sponsorship_create_request_model: Option<
            models::OrganizationSponsorshipCreateRequestModel,
        >,
    ) -> Result<(), Error>;

    /// GET /organization/sponsorship/self-hosted/{orgId}/sponsored
    async fn get_sponsored_organizations<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationSponsorshipInvitesResponseModelListResponseModel, Error>;

    /// DELETE /organization/sponsorship/self-hosted/{sponsoringOrgId}
    async fn revoke_sponsorship<'a>(&self, sponsoring_org_id: uuid::Uuid) -> Result<(), Error>;
}

pub struct SelfHostedOrganizationSponsorshipsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl SelfHostedOrganizationSponsorshipsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl SelfHostedOrganizationSponsorshipsApi for SelfHostedOrganizationSponsorshipsApiClient {
    async fn admin_initiated_revoke_sponsorship<'a>(
        &self,
        organization_id: uuid::Uuid,
        sponsored_friendly_name: &'a str,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organization/sponsorship/self-hosted/{organizationId}/{sponsoredFriendlyName}/revoke",
            local_var_configuration.base_path,
            organizationId = organization_id,
            sponsoredFriendlyName = crate::apis::urlencode(sponsored_friendly_name)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn create_sponsorship<'a>(
        &self,
        sponsoring_org_id: uuid::Uuid,
        organization_sponsorship_create_request_model: Option<
            models::OrganizationSponsorshipCreateRequestModel,
        >,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organization/sponsorship/self-hosted/{sponsoringOrgId}/families-for-enterprise",
            local_var_configuration.base_path,
            sponsoringOrgId = sponsoring_org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder =
            local_var_req_builder.json(&organization_sponsorship_create_request_model);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn get_sponsored_organizations<'a>(
        &self,
        org_id: uuid::Uuid,
    ) -> Result<models::OrganizationSponsorshipInvitesResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organization/sponsorship/self-hosted/{orgId}/sponsored",
            local_var_configuration.base_path,
            orgId = org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn revoke_sponsorship<'a>(&self, sponsoring_org_id: uuid::Uuid) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organization/sponsorship/self-hosted/{sponsoringOrgId}",
            local_var_configuration.base_path,
            sponsoringOrgId = sponsoring_org_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }
}
