/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::{
    apis::{AuthRequired, ContentType, ResponseContent},
    models,
};

#[cfg_attr(feature = "mockall", automock)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait ServiceAccountsApi: Send + Sync {
    /// POST /service-accounts/delete
    async fn bulk_delete<'a>(
        &self,
        uuid_colon_colon_uuid: Option<Vec<uuid::Uuid>>,
    ) -> Result<models::BulkDeleteResponseModelListResponseModel, Error>;

    /// POST /organizations/{organizationId}/service-accounts
    async fn create<'a>(
        &self,
        organization_id: uuid::Uuid,
        service_account_create_request_model: Option<models::ServiceAccountCreateRequestModel>,
    ) -> Result<models::ServiceAccountResponseModel, Error>;

    /// POST /service-accounts/{id}/access-tokens
    async fn create_access_token<'a>(
        &self,
        id: uuid::Uuid,
        access_token_create_request_model: Option<models::AccessTokenCreateRequestModel>,
    ) -> Result<models::AccessTokenCreationResponseModel, Error>;

    /// GET /service-accounts/{id}/access-tokens
    async fn get_access_tokens<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::AccessTokenResponseModelListResponseModel, Error>;

    /// GET /service-accounts/{id}
    async fn get_by_service_account_id<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ServiceAccountResponseModel, Error>;

    /// GET /organizations/{organizationId}/service-accounts
    async fn list_by_organization<'a>(
        &self,
        organization_id: uuid::Uuid,
        include_access_to_secrets: Option<bool>,
    ) -> Result<models::ServiceAccountSecretsDetailsResponseModelListResponseModel, Error>;

    /// POST /service-accounts/{id}/access-tokens/revoke
    async fn revoke_access_tokens<'a>(
        &self,
        id: uuid::Uuid,
        revoke_access_tokens_request: Option<models::RevokeAccessTokensRequest>,
    ) -> Result<(), Error>;

    /// PUT /service-accounts/{id}
    async fn update<'a>(
        &self,
        id: uuid::Uuid,
        service_account_update_request_model: Option<models::ServiceAccountUpdateRequestModel>,
    ) -> Result<models::ServiceAccountResponseModel, Error>;
}

pub struct ServiceAccountsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ServiceAccountsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
impl ServiceAccountsApi for ServiceAccountsApiClient {
    async fn bulk_delete<'a>(
        &self,
        uuid_colon_colon_uuid: Option<Vec<uuid::Uuid>>,
    ) -> Result<models::BulkDeleteResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/delete",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&uuid_colon_colon_uuid);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn create<'a>(
        &self,
        organization_id: uuid::Uuid,
        service_account_create_request_model: Option<models::ServiceAccountCreateRequestModel>,
    ) -> Result<models::ServiceAccountResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/service-accounts",
            local_var_configuration.base_path,
            organizationId = organization_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&service_account_create_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn create_access_token<'a>(
        &self,
        id: uuid::Uuid,
        access_token_create_request_model: Option<models::AccessTokenCreateRequestModel>,
    ) -> Result<models::AccessTokenCreationResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/access-tokens",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&access_token_create_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_access_tokens<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::AccessTokenResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/access-tokens",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn get_by_service_account_id<'a>(
        &self,
        id: uuid::Uuid,
    ) -> Result<models::ServiceAccountResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn list_by_organization<'a>(
        &self,
        organization_id: uuid::Uuid,
        include_access_to_secrets: Option<bool>,
    ) -> Result<models::ServiceAccountSecretsDetailsResponseModelListResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organizationId}/service-accounts",
            local_var_configuration.base_path,
            organizationId = organization_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = include_access_to_secrets {
            local_var_req_builder = local_var_req_builder
                .query(&[("includeAccessToSecrets", &param_value.to_string())]);
        }
        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }

    async fn revoke_access_tokens<'a>(
        &self,
        id: uuid::Uuid,
        revoke_access_tokens_request: Option<models::RevokeAccessTokensRequest>,
    ) -> Result<(), Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}/access-tokens/revoke",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&revoke_access_tokens_request);

        bitwarden_api_base::process_with_empty_response(local_var_req_builder).await
    }

    async fn update<'a>(
        &self,
        id: uuid::Uuid,
        service_account_update_request_model: Option<models::ServiceAccountUpdateRequestModel>,
    ) -> Result<models::ServiceAccountResponseModel, Error> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/service-accounts/{id}",
            local_var_configuration.base_path,
            id = id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.with_extension(AuthRequired::Bearer);
        local_var_req_builder = local_var_req_builder.json(&service_account_update_request_model);

        bitwarden_api_base::process_with_json_response(local_var_req_builder).await
    }
}
