// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordType {
    #[prost(int32, tag = "1")]
    pub record_type_id: i32,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(enumeration = "RecordTypeScope", tag = "3")]
    pub scope: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordTypesRequest {
    #[prost(bool, tag = "1")]
    pub standard: bool,
    #[prost(bool, tag = "2")]
    pub user: bool,
    #[prost(bool, tag = "3")]
    pub enterprise: bool,
    #[prost(bool, tag = "4")]
    pub pam: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordTypesResponse {
    #[prost(message, repeated, tag = "1")]
    pub record_types: ::prost::alloc::vec::Vec<RecordType>,
    #[prost(int32, tag = "2")]
    pub standard_counter: i32,
    #[prost(int32, tag = "3")]
    pub user_counter: i32,
    #[prost(int32, tag = "4")]
    pub enterprise_counter: i32,
    #[prost(int32, tag = "5")]
    pub pam_counter: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordTypeModifyResponse {
    #[prost(int32, tag = "1")]
    pub record_type_id: i32,
    #[prost(int32, tag = "2")]
    pub counter: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordsGetRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub record_uids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(int64, tag = "2")]
    pub client_time: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Record {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RecordKeyType", tag = "3")]
    pub record_key_type: i32,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub extra: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "6")]
    pub version: i32,
    #[prost(int64, tag = "7")]
    pub client_modified_time: i64,
    #[prost(int64, tag = "8")]
    pub revision: i64,
    #[prost(bytes = "vec", repeated, tag = "9")]
    pub file_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FolderRecordKey {
    #[prost(bytes = "vec", tag = "1")]
    pub folder_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Folder {
    #[prost(bytes = "vec", tag = "1")]
    pub folder_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub folder_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RecordKeyType", tag = "3")]
    pub folder_key_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Team {
    #[prost(bytes = "vec", tag = "1")]
    pub team_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub team_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub team_private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RecordKeyType", tag = "4")]
    pub team_key_type: i32,
    #[prost(message, repeated, tag = "5")]
    pub folders: ::prost::alloc::vec::Vec<Folder>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsGetResponse {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<Record>,
    #[prost(message, repeated, tag = "2")]
    pub folder_record_keys: ::prost::alloc::vec::Vec<FolderRecordKey>,
    #[prost(message, repeated, tag = "3")]
    pub folders: ::prost::alloc::vec::Vec<Folder>,
    #[prost(message, repeated, tag = "4")]
    pub teams: ::prost::alloc::vec::Vec<Team>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordLink {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordAudit {
    #[prost(int32, tag = "1")]
    pub version: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecurityData {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecurityScoreData {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordAdd {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub client_modified_time: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub non_shared_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RecordFolderType", tag = "6")]
    pub folder_type: i32,
    #[prost(bytes = "vec", tag = "7")]
    pub folder_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "8")]
    pub folder_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "9")]
    pub record_links: ::prost::alloc::vec::Vec<RecordLink>,
    #[prost(message, optional, tag = "10")]
    pub audit: ::core::option::Option<RecordAudit>,
    #[prost(message, optional, tag = "11")]
    pub security_data: ::core::option::Option<SecurityData>,
    #[prost(message, optional, tag = "12")]
    pub security_score_data: ::core::option::Option<SecurityScoreData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsAddRequest {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<RecordAdd>,
    #[prost(int64, tag = "2")]
    pub client_time: i64,
    #[prost(enumeration = "RecordKeyType", tag = "3")]
    pub security_data_key_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordUpdate {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub client_modified_time: i64,
    #[prost(int64, tag = "3")]
    pub revision: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub non_shared_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "6")]
    pub record_links_add: ::prost::alloc::vec::Vec<RecordLink>,
    #[prost(bytes = "vec", repeated, tag = "7")]
    pub record_links_remove: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "8")]
    pub audit: ::core::option::Option<RecordAudit>,
    #[prost(message, optional, tag = "9")]
    pub security_data: ::core::option::Option<SecurityData>,
    #[prost(message, optional, tag = "10")]
    pub security_score_data: ::core::option::Option<SecurityScoreData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsUpdateRequest {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<RecordUpdate>,
    #[prost(int64, tag = "2")]
    pub client_time: i64,
    #[prost(enumeration = "RecordKeyType", tag = "3")]
    pub security_data_key_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordFileForConversion {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub file_file_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub thumb_file_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub link_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordFolderForConversion {
    #[prost(bytes = "vec", tag = "1")]
    pub folder_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_folder_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordConvertToV3 {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub client_modified_time: i64,
    #[prost(int64, tag = "3")]
    pub revision: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub non_shared_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub audit: ::core::option::Option<RecordAudit>,
    #[prost(message, repeated, tag = "7")]
    pub record_file: ::prost::alloc::vec::Vec<RecordFileForConversion>,
    #[prost(message, repeated, tag = "8")]
    pub folder_key: ::prost::alloc::vec::Vec<RecordFolderForConversion>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsConvertToV3Request {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<RecordConvertToV3>,
    #[prost(int64, tag = "2")]
    pub client_time: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordsRemoveRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordRevert {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub revert_to_revision: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsRevertRequest {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<RecordRevert>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordLinkError {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RecordModifyResult", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordModifyStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RecordModifyResult", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub link_errors: ::prost::alloc::vec::Vec<RecordLinkError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsModifyResponse {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<RecordModifyStatus>,
    #[prost(int64, tag = "2")]
    pub revision: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordAddAuditData {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub revision: i64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "4")]
    pub version: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddAuditDataRequest {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<RecordAddAuditData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct File {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "4")]
    pub file_size: i64,
    #[prost(int32, tag = "5")]
    pub thumb_size: i32,
    #[prost(bool, tag = "6")]
    pub is_script: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesAddRequest {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<File>,
    #[prost(int64, tag = "2")]
    pub client_time: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileAddStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "FileAddResult", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub parameters: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub thumbnail_parameters: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub success_status_code: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesAddResponse {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<FileAddStatus>,
    #[prost(int64, tag = "2")]
    pub revision: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FilesGetRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub record_uids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag = "2")]
    pub for_thumbnails: bool,
    #[prost(string, tag = "3")]
    pub emergency_access_account_owner: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileGetStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "FileGetResult", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub success_status_code: i32,
    #[prost(enumeration = "RecordKeyType", tag = "5")]
    pub file_key_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesGetResponse {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<FileGetStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplicationAddRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub app_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub client_modified_time: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub audit: ::core::option::Option<RecordAudit>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRecordDataWithAccessInfoRequest {
    #[prost(int64, tag = "1")]
    pub client_time: i64,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub record_uid: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(enumeration = "RecordDetailsInclude", tag = "3")]
    pub record_details_include: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserPermission {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub owner: bool,
    #[prost(bool, tag = "3")]
    pub share_admin: bool,
    #[prost(bool, tag = "4")]
    pub sharable: bool,
    #[prost(bool, tag = "5")]
    pub editable: bool,
    #[prost(bool, tag = "6")]
    pub awaiting_approval: bool,
    #[prost(int64, tag = "7")]
    pub expiration: i64,
    #[prost(bytes = "vec", tag = "8")]
    pub account_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "TimerNotificationType", tag = "9")]
    pub timer_notification_type: i32,
    #[prost(bool, tag = "10")]
    pub rotate_on_expiration: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SharedFolderPermission {
    #[prost(bytes = "vec", tag = "1")]
    pub shared_folder_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub resharable: bool,
    #[prost(bool, tag = "3")]
    pub editable: bool,
    #[prost(int64, tag = "4")]
    pub revision: i64,
    #[prost(int64, tag = "5")]
    pub expiration: i64,
    #[prost(enumeration = "TimerNotificationType", tag = "6")]
    pub timer_notification_type: i32,
    #[prost(bool, tag = "7")]
    pub rotate_on_expiration: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordData {
    #[prost(int64, tag = "1")]
    pub revision: i64,
    #[prost(int32, tag = "2")]
    pub version: i32,
    #[prost(bool, tag = "3")]
    pub shared: bool,
    #[prost(string, tag = "4")]
    pub encrypted_record_data: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub encrypted_extra_data: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub client_modified_time: i64,
    #[prost(string, tag = "7")]
    pub non_shared_data: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "8")]
    pub linked_record_data: ::prost::alloc::vec::Vec<RecordData>,
    #[prost(bytes = "vec", repeated, tag = "9")]
    pub file_id: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(int64, tag = "10")]
    pub file_size: i64,
    #[prost(int64, tag = "11")]
    pub thumbnail_size: i64,
    #[prost(enumeration = "RecordKeyType", tag = "12")]
    pub record_key_type: i32,
    #[prost(bytes = "vec", tag = "13")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "14")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordDataWithAccessInfo {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub record_data: ::core::option::Option<RecordData>,
    #[prost(message, repeated, tag = "3")]
    pub user_permission: ::prost::alloc::vec::Vec<UserPermission>,
    #[prost(message, repeated, tag = "4")]
    pub shared_folder_permission: ::prost::alloc::vec::Vec<SharedFolderPermission>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRecordDataWithAccessInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub record_data_with_access_info: ::prost::alloc::vec::Vec<RecordDataWithAccessInfo>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub no_permission_record_uid: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IsObjectShareAdmin {
    #[prost(bytes = "vec", tag = "1")]
    pub uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub is_admin: bool,
    #[prost(enumeration = "CheckShareAdminObjectType", tag = "3")]
    pub object_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AmIShareAdmin {
    #[prost(message, repeated, tag = "1")]
    pub is_object_share_admin: ::prost::alloc::vec::Vec<IsObjectShareAdmin>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordShareUpdateRequest {
    #[prost(message, repeated, tag = "1")]
    pub add_shared_record: ::prost::alloc::vec::Vec<SharedRecord>,
    #[prost(message, repeated, tag = "2")]
    pub update_shared_record: ::prost::alloc::vec::Vec<SharedRecord>,
    #[prost(message, repeated, tag = "3")]
    pub remove_shared_record: ::prost::alloc::vec::Vec<SharedRecord>,
    #[prost(string, tag = "4")]
    pub pt: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SharedRecord {
    #[prost(string, tag = "1")]
    pub to_username: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub shared_folder_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub team_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "6")]
    pub editable: bool,
    #[prost(bool, tag = "7")]
    pub shareable: bool,
    #[prost(bool, tag = "8")]
    pub transfer: bool,
    #[prost(bool, tag = "9")]
    pub use_ecc_key: bool,
    #[prost(bool, tag = "10")]
    pub remove_vault_data: bool,
    #[prost(int64, tag = "11")]
    pub expiration: i64,
    #[prost(enumeration = "TimerNotificationType", tag = "12")]
    pub timer_notification_type: i32,
    #[prost(bool, tag = "13")]
    pub rotate_on_expiration: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordShareUpdateResponse {
    #[prost(message, repeated, tag = "1")]
    pub add_shared_record_status: ::prost::alloc::vec::Vec<SharedRecordStatus>,
    #[prost(message, repeated, tag = "2")]
    pub update_shared_record_status: ::prost::alloc::vec::Vec<SharedRecordStatus>,
    #[prost(message, repeated, tag = "3")]
    pub remove_shared_record_status: ::prost::alloc::vec::Vec<SharedRecordStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SharedRecordStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRecordPermissionsRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub record_uids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag = "2")]
    pub is_share_admin: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRecordPermissionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub record_permissions: ::prost::alloc::vec::Vec<RecordPermission>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordPermission {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub owner: bool,
    #[prost(bool, tag = "3")]
    pub can_edit: bool,
    #[prost(bool, tag = "4")]
    pub can_share: bool,
    #[prost(bool, tag = "5")]
    pub can_transfer: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetShareObjectsRequest {
    #[prost(string, tag = "1")]
    pub start_with: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub contains: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub filtered: bool,
    #[prost(bytes = "vec", tag = "4")]
    pub shared_folder_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetShareObjectsResponse {
    #[prost(message, repeated, tag = "1")]
    pub share_relationships: ::prost::alloc::vec::Vec<ShareUser>,
    #[prost(message, repeated, tag = "2")]
    pub share_family_users: ::prost::alloc::vec::Vec<ShareUser>,
    #[prost(message, repeated, tag = "3")]
    pub share_enterprise_users: ::prost::alloc::vec::Vec<ShareUser>,
    #[prost(message, repeated, tag = "4")]
    pub share_teams: ::prost::alloc::vec::Vec<ShareTeam>,
    #[prost(message, repeated, tag = "5")]
    pub share_mc_teams: ::prost::alloc::vec::Vec<ShareTeam>,
    #[prost(message, repeated, tag = "6")]
    pub share_mc_enterprise_users: ::prost::alloc::vec::Vec<ShareUser>,
    #[prost(message, repeated, tag = "7")]
    pub share_enterprise_names: ::prost::alloc::vec::Vec<ShareEnterprise>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareUser {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub fullname: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub enterprise_id: i32,
    #[prost(enumeration = "ShareStatus", tag = "4")]
    pub status: i32,
    #[prost(bool, tag = "5")]
    pub is_share_admin: bool,
    #[prost(bool, tag = "6")]
    pub is_admin_of_shared_folder_owner: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareTeam {
    #[prost(string, tag = "1")]
    pub teamname: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub enterprise_id: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub team_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareEnterprise {
    #[prost(string, tag = "1")]
    pub enterprisename: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub enterprise_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsOnwershipTransferRequest {
    #[prost(message, repeated, tag = "1")]
    pub transfer_records: ::prost::alloc::vec::Vec<TransferRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransferRecord {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub record_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub use_ecc_key: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsOnwershipTransferResponse {
    #[prost(message, repeated, tag = "1")]
    pub transfer_record_status: ::prost::alloc::vec::Vec<TransferRecordStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransferRecordStatus {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsUnshareRequest {
    #[prost(message, repeated, tag = "1")]
    pub shared_folders: ::prost::alloc::vec::Vec<RecordsUnshareFolder>,
    #[prost(message, repeated, tag = "2")]
    pub users: ::prost::alloc::vec::Vec<RecordsUnshareUser>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordsUnshareResponse {
    #[prost(message, repeated, tag = "1")]
    pub shared_folders: ::prost::alloc::vec::Vec<RecordsUnshareFolderStatus>,
    #[prost(message, repeated, tag = "2")]
    pub users: ::prost::alloc::vec::Vec<RecordsUnshareUserStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordsUnshareFolder {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub shared_folder_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordsUnshareUser {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub account_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordsUnshareFolderStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub shared_folder_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordsUnshareUserStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub record_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub account_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimedAccessCallbackPayload {
    #[prost(enumeration = "TimeLimitedAccessType", tag = "1")]
    pub time_limited_access_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeLimitedAccessRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub account_uid: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub team_uid: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub record_uid: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "4")]
    pub shared_object_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "TimeLimitedAccessType", tag = "5")]
    pub time_limited_access_type: i32,
    #[prost(int64, tag = "6")]
    pub expiration: i64,
    #[prost(enumeration = "TimerNotificationType", tag = "7")]
    pub timer_notification_type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeLimitedAccessStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeLimitedAccessResponse {
    #[prost(int64, tag = "1")]
    pub revision: i64,
    #[prost(message, repeated, tag = "2")]
    pub user_access_status: ::prost::alloc::vec::Vec<TimeLimitedAccessStatus>,
    #[prost(message, repeated, tag = "3")]
    pub team_access_status: ::prost::alloc::vec::Vec<TimeLimitedAccessStatus>,
    #[prost(message, repeated, tag = "4")]
    pub record_access_status: ::prost::alloc::vec::Vec<TimeLimitedAccessStatus>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordTypeScope {
    RtStandard = 0,
    RtUser = 1,
    RtEnterprise = 2,
    RtPam = 3,
    RtPamConfiguration = 4,
}
impl RecordTypeScope {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RtStandard => "RT_STANDARD",
            Self::RtUser => "RT_USER",
            Self::RtEnterprise => "RT_ENTERPRISE",
            Self::RtPam => "RT_PAM",
            Self::RtPamConfiguration => "RT_PAM_CONFIGURATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RT_STANDARD" => Some(Self::RtStandard),
            "RT_USER" => Some(Self::RtUser),
            "RT_ENTERPRISE" => Some(Self::RtEnterprise),
            "RT_PAM" => Some(Self::RtPam),
            "RT_PAM_CONFIGURATION" => Some(Self::RtPamConfiguration),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordKeyType {
    NoKey = 0,
    EncryptedByDataKey = 1,
    EncryptedByPublicKey = 2,
    EncryptedByDataKeyGcm = 3,
    EncryptedByPublicKeyEcc = 4,
    EncryptedByRootKeyCbc = 5,
    EncryptedByRootKeyGcm = 6,
}
impl RecordKeyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoKey => "NO_KEY",
            Self::EncryptedByDataKey => "ENCRYPTED_BY_DATA_KEY",
            Self::EncryptedByPublicKey => "ENCRYPTED_BY_PUBLIC_KEY",
            Self::EncryptedByDataKeyGcm => "ENCRYPTED_BY_DATA_KEY_GCM",
            Self::EncryptedByPublicKeyEcc => "ENCRYPTED_BY_PUBLIC_KEY_ECC",
            Self::EncryptedByRootKeyCbc => "ENCRYPTED_BY_ROOT_KEY_CBC",
            Self::EncryptedByRootKeyGcm => "ENCRYPTED_BY_ROOT_KEY_GCM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NO_KEY" => Some(Self::NoKey),
            "ENCRYPTED_BY_DATA_KEY" => Some(Self::EncryptedByDataKey),
            "ENCRYPTED_BY_PUBLIC_KEY" => Some(Self::EncryptedByPublicKey),
            "ENCRYPTED_BY_DATA_KEY_GCM" => Some(Self::EncryptedByDataKeyGcm),
            "ENCRYPTED_BY_PUBLIC_KEY_ECC" => Some(Self::EncryptedByPublicKeyEcc),
            "ENCRYPTED_BY_ROOT_KEY_CBC" => Some(Self::EncryptedByRootKeyCbc),
            "ENCRYPTED_BY_ROOT_KEY_GCM" => Some(Self::EncryptedByRootKeyGcm),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordFolderType {
    UserFolder = 0,
    SharedFolder = 1,
    SharedFolderFolder = 2,
}
impl RecordFolderType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UserFolder => "user_folder",
            Self::SharedFolder => "shared_folder",
            Self::SharedFolderFolder => "shared_folder_folder",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "user_folder" => Some(Self::UserFolder),
            "shared_folder" => Some(Self::SharedFolder),
            "shared_folder_folder" => Some(Self::SharedFolderFolder),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordModifyResult {
    RsSuccess = 0,
    RsOutOfSync = 1,
    RsAccessDenied = 2,
    RsShareDenied = 3,
    RsRecordExists = 4,
    RsOldRecordVersionType = 5,
    RsNewRecordVersionType = 6,
    RsFilesNotMatch = 7,
    RsRecordNotShareable = 8,
    RsAttachmentNotShareable = 9,
    RsFileLimitReached = 10,
    RsSizeExceededLimit = 11,
    RsOnlyOwnerCanModifyScripts = 12,
}
impl RecordModifyResult {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RsSuccess => "RS_SUCCESS",
            Self::RsOutOfSync => "RS_OUT_OF_SYNC",
            Self::RsAccessDenied => "RS_ACCESS_DENIED",
            Self::RsShareDenied => "RS_SHARE_DENIED",
            Self::RsRecordExists => "RS_RECORD_EXISTS",
            Self::RsOldRecordVersionType => "RS_OLD_RECORD_VERSION_TYPE",
            Self::RsNewRecordVersionType => "RS_NEW_RECORD_VERSION_TYPE",
            Self::RsFilesNotMatch => "RS_FILES_NOT_MATCH",
            Self::RsRecordNotShareable => "RS_RECORD_NOT_SHAREABLE",
            Self::RsAttachmentNotShareable => "RS_ATTACHMENT_NOT_SHAREABLE",
            Self::RsFileLimitReached => "RS_FILE_LIMIT_REACHED",
            Self::RsSizeExceededLimit => "RS_SIZE_EXCEEDED_LIMIT",
            Self::RsOnlyOwnerCanModifyScripts => "RS_ONLY_OWNER_CAN_MODIFY_SCRIPTS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RS_SUCCESS" => Some(Self::RsSuccess),
            "RS_OUT_OF_SYNC" => Some(Self::RsOutOfSync),
            "RS_ACCESS_DENIED" => Some(Self::RsAccessDenied),
            "RS_SHARE_DENIED" => Some(Self::RsShareDenied),
            "RS_RECORD_EXISTS" => Some(Self::RsRecordExists),
            "RS_OLD_RECORD_VERSION_TYPE" => Some(Self::RsOldRecordVersionType),
            "RS_NEW_RECORD_VERSION_TYPE" => Some(Self::RsNewRecordVersionType),
            "RS_FILES_NOT_MATCH" => Some(Self::RsFilesNotMatch),
            "RS_RECORD_NOT_SHAREABLE" => Some(Self::RsRecordNotShareable),
            "RS_ATTACHMENT_NOT_SHAREABLE" => Some(Self::RsAttachmentNotShareable),
            "RS_FILE_LIMIT_REACHED" => Some(Self::RsFileLimitReached),
            "RS_SIZE_EXCEEDED_LIMIT" => Some(Self::RsSizeExceededLimit),
            "RS_ONLY_OWNER_CAN_MODIFY_SCRIPTS" => Some(Self::RsOnlyOwnerCanModifyScripts),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileAddResult {
    FaSuccess = 0,
    FaError = 1,
}
impl FileAddResult {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FaSuccess => "FA_SUCCESS",
            Self::FaError => "FA_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FA_SUCCESS" => Some(Self::FaSuccess),
            "FA_ERROR" => Some(Self::FaError),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileGetResult {
    FgSuccess = 0,
    FgError = 1,
    FgAccessDenied = 2,
}
impl FileGetResult {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FgSuccess => "FG_SUCCESS",
            Self::FgError => "FG_ERROR",
            Self::FgAccessDenied => "FG_ACCESS_DENIED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FG_SUCCESS" => Some(Self::FgSuccess),
            "FG_ERROR" => Some(Self::FgError),
            "FG_ACCESS_DENIED" => Some(Self::FgAccessDenied),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordDetailsInclude {
    DataPlusShare = 0,
    DataOnly = 1,
    ShareOnly = 2,
}
impl RecordDetailsInclude {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DataPlusShare => "DATA_PLUS_SHARE",
            Self::DataOnly => "DATA_ONLY",
            Self::ShareOnly => "SHARE_ONLY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_PLUS_SHARE" => Some(Self::DataPlusShare),
            "DATA_ONLY" => Some(Self::DataOnly),
            "SHARE_ONLY" => Some(Self::ShareOnly),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CheckShareAdminObjectType {
    CheckSaInvalidType = 0,
    CheckSaOnSf = 1,
    CheckSaOnRecord = 2,
}
impl CheckShareAdminObjectType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CheckSaInvalidType => "CHECK_SA_INVALID_TYPE",
            Self::CheckSaOnSf => "CHECK_SA_ON_SF",
            Self::CheckSaOnRecord => "CHECK_SA_ON_RECORD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHECK_SA_INVALID_TYPE" => Some(Self::CheckSaInvalidType),
            "CHECK_SA_ON_SF" => Some(Self::CheckSaOnSf),
            "CHECK_SA_ON_RECORD" => Some(Self::CheckSaOnRecord),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShareStatus {
    Active = 0,
    Block = 1,
    Invited = 2,
}
impl ShareStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Active => "ACTIVE",
            Self::Block => "BLOCK",
            Self::Invited => "INVITED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVE" => Some(Self::Active),
            "BLOCK" => Some(Self::Block),
            "INVITED" => Some(Self::Invited),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecordTransactionType {
    RttGeneral = 0,
    RttRotation = 1,
}
impl RecordTransactionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RttGeneral => "RTT_GENERAL",
            Self::RttRotation => "RTT_ROTATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RTT_GENERAL" => Some(Self::RttGeneral),
            "RTT_ROTATION" => Some(Self::RttRotation),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TimeLimitedAccessType {
    InvalidTimeLimitedAccessType = 0,
    UserAccessToRecord = 1,
    UserOrTeamAccessToSharedfolder = 2,
    RecordAccessToSharedfolder = 3,
    UserAccessToSharedfolder = 4,
    TeamAccessToSharedfolder = 5,
}
impl TimeLimitedAccessType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InvalidTimeLimitedAccessType => "INVALID_TIME_LIMITED_ACCESS_TYPE",
            Self::UserAccessToRecord => "USER_ACCESS_TO_RECORD",
            Self::UserOrTeamAccessToSharedfolder => "USER_OR_TEAM_ACCESS_TO_SHAREDFOLDER",
            Self::RecordAccessToSharedfolder => "RECORD_ACCESS_TO_SHAREDFOLDER",
            Self::UserAccessToSharedfolder => "USER_ACCESS_TO_SHAREDFOLDER",
            Self::TeamAccessToSharedfolder => "TEAM_ACCESS_TO_SHAREDFOLDER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INVALID_TIME_LIMITED_ACCESS_TYPE" => Some(Self::InvalidTimeLimitedAccessType),
            "USER_ACCESS_TO_RECORD" => Some(Self::UserAccessToRecord),
            "USER_OR_TEAM_ACCESS_TO_SHAREDFOLDER" => Some(Self::UserOrTeamAccessToSharedfolder),
            "RECORD_ACCESS_TO_SHAREDFOLDER" => Some(Self::RecordAccessToSharedfolder),
            "USER_ACCESS_TO_SHAREDFOLDER" => Some(Self::UserAccessToSharedfolder),
            "TEAM_ACCESS_TO_SHAREDFOLDER" => Some(Self::TeamAccessToSharedfolder),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TimerNotificationType {
    NotificationOff = 0,
    NotifyOwner = 1,
    NotifyPrivilegedUsers = 2,
}
impl TimerNotificationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotificationOff => "NOTIFICATION_OFF",
            Self::NotifyOwner => "NOTIFY_OWNER",
            Self::NotifyPrivilegedUsers => "NOTIFY_PRIVILEGED_USERS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOTIFICATION_OFF" => Some(Self::NotificationOff),
            "NOTIFY_OWNER" => Some(Self::NotifyOwner),
            "NOTIFY_PRIVILEGED_USERS" => Some(Self::NotifyPrivilegedUsers),
            _ => None,
        }
    }
}
