//! A high-entropy secret is a wrapper around secret bytes that are guaranteed to be high-entropy,
//! and therefore safe to use as input keying material for a cheap KDF (such as the one used by the
//! `SecretProtectedKeyEnvelope`).
//!
//! Examples of high-entropy secrets are a random URL-fragment secret, a derived key, or random
//! bytes. They are unlike low-entropy secrets such as PINs or passwords, which can be brute-forced
//! and therefore require a memory- or compute-hard KDF.

#[cfg(feature = "wasm")]
use bitwarden_encoding::B64;
use bitwarden_sensitive_value::{ExposeSensitive, Sensitive, SensitiveSlice};
use rand::Rng;
use thiserror::Error;
#[cfg(feature = "wasm")]
use wasm_bindgen::convert::{FromWasmAbi, IntoWasmAbi, OptionFromWasmAbi};
use zeroize::Zeroizing;

/// Minimum accepted secret length in bytes. 16 bytes = 128 bits of headroom for a uniformly
/// random secret, matching the security level a cheap KDF assumes.
const MIN_SECRET_LENGTH: usize = 16;

/// A high entropy secret, generated from a CSPRNG or derived from a high-entropy key. This MUST NOT
/// be:
/// - An UTF-8 or ASCII string, even if Base64-encoded or hex-encoded high-entropy bytes
/// - A low-entropy secret
/// - A static key
///
/// Approved sources are:
/// - A PRF derived from windows-hello biometrics in Bitwarden-Desktop
/// - A PRF output from a passkey with the hmac-secret extension
/// - Key-connector-stored bytes
/// - A high entropy secret generated with `HighEntropySecret::make()`
pub trait HighEntropySecretSource {
    /// Returns the secret bytes as a redacted [`SensitiveSlice`].
    fn provide_high_entropy_bytes(&self) -> SensitiveSlice<'_>;
}

/// A secret that is guaranteed to be high-entropy, and therefore safe to use as input keying
/// material for a cheap KDF.
#[derive(Clone)]
pub struct HighEntropySecret {
    secret: Zeroizing<Vec<u8>>,
}

impl HighEntropySecret {
    /// Constructs a `HighEntropySecret` from any [`HighEntropySecretSource`], whose implementation
    /// guarantees the provided bytes are high-entropy.
    pub fn from<T: HighEntropySecretSource>(secret: T) -> Self {
        Self::from_internal(secret.provide_high_entropy_bytes().expose_owned())
    }

    // Creates a new `HighEntropySecret` from the provided bytes, without validation. The caller is
    // responsible for ensuring that the bytes are high-entropy and not derived from a low-entropy
    // source!
    pub(crate) fn from_internal(secret: &[u8]) -> Self {
        Self {
            secret: Zeroizing::new(secret.to_vec()),
        }
    }

    /// Generates a new high-entropy secret of the desired size, using cryptographically secure
    /// random bytes. The generated bytes are high-entropy by construction.
    ///
    /// `desired_size` should be at least 16 bytes to provide adequate security headroom.
    pub fn make(desired_size: usize) -> Result<Self, HighEntropySecretError> {
        if desired_size < MIN_SECRET_LENGTH {
            return Err(HighEntropySecretError::TooShort);
        }

        let mut secret = Zeroizing::new(vec![0u8; desired_size]);
        rand::rng().fill_bytes(secret.as_mut_slice());
        Ok(Self { secret })
    }

    /// Returns the secret bytes as a redacted [`SensitiveSlice`]. Not public since callers should
    /// not handle the raw secret material directly.
    pub(crate) fn as_bytes(&self) -> SensitiveSlice<'_> {
        Sensitive::from(self.secret.as_slice())
    }
}

// Manually implemented so the secret material is never printed.
impl std::fmt::Debug for HighEntropySecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("HighEntropySecret").finish()
    }
}

/// Errors that can occur when constructing a [`HighEntropySecret`].
#[derive(Debug, Error)]
pub enum HighEntropySecretError {
    /// The provided secret is too short to be used as a high-entropy secret.
    #[error("Secret is too short")]
    TooShort,
}

#[cfg(feature = "wasm")]
#[wasm_bindgen::prelude::wasm_bindgen(typescript_custom_section)]
const TS_CUSTOM_TYPES: &'static str = r#"
export type HighEntropySecret = Tagged<String, "HighEntropySecret">;
"#;

#[cfg(feature = "wasm")]
impl wasm_bindgen::describe::WasmDescribe for HighEntropySecret {
    fn describe() {
        <String as wasm_bindgen::describe::WasmDescribe>::describe();
    }
}

#[cfg(feature = "wasm")]
impl FromWasmAbi for HighEntropySecret {
    type Abi = <String as FromWasmAbi>::Abi;

    unsafe fn from_abi(abi: Self::Abi) -> Self {
        use wasm_bindgen::UnwrapThrowExt;
        let string = unsafe { String::from_abi(abi) };
        let b64 = B64::try_from(string).unwrap_throw();
        HighEntropySecret::from_internal(b64.as_bytes())
    }
}

#[cfg(feature = "wasm")]
impl OptionFromWasmAbi for HighEntropySecret {
    fn is_none(abi: &Self::Abi) -> bool {
        <String as OptionFromWasmAbi>::is_none(abi)
    }
}

#[cfg(feature = "wasm")]
impl IntoWasmAbi for HighEntropySecret {
    type Abi = <String as IntoWasmAbi>::Abi;

    fn into_abi(self) -> Self::Abi {
        let string: String = B64::from(self.secret.as_slice()).to_string();
        string.into_abi()
    }
}

#[cfg(test)]
mod tests {
    use bitwarden_sensitive_value::ExposeSensitive;

    use super::*;

    #[test]
    fn test_debug_does_not_leak_secret() {
        let secret = HighEntropySecret::make(32).unwrap();
        let debug = format!("{secret:?}");
        assert_eq!(debug, "HighEntropySecret");
    }

    #[test]
    fn test_make_rejects_secret_below_minimum_length() {
        for size in 0..MIN_SECRET_LENGTH {
            assert!(
                matches!(
                    HighEntropySecret::make(size),
                    Err(HighEntropySecretError::TooShort)
                ),
                "expected size {size} to be rejected as too short"
            );
        }
    }

    #[test]
    fn test_make_accepts_secret_at_minimum_length() {
        let secret = HighEntropySecret::make(MIN_SECRET_LENGTH).unwrap();
        assert_eq!(secret.as_bytes().expose_owned().len(), MIN_SECRET_LENGTH);
    }

    #[test]
    fn test_make_produces_secret_of_requested_length() {
        for size in [16, 32, 64, 128] {
            let secret = HighEntropySecret::make(size).unwrap();
            assert_eq!(secret.as_bytes().expose_owned().len(), size);
        }
    }

    #[test]
    fn test_make_produces_distinct_secrets() {
        let first = HighEntropySecret::make(32).unwrap();
        let second = HighEntropySecret::make(32).unwrap();
        // Two independently generated secrets are overwhelmingly unlikely to collide.
        assert_ne!(
            first.as_bytes().expose_owned(),
            second.as_bytes().expose_owned()
        );
    }

    #[test]
    fn test_from_bytes_preserves_secret() {
        let bytes = vec![7u8; 32];
        let secret = HighEntropySecret::from_internal(bytes.as_slice());
        assert_eq!(secret.as_bytes().expose_owned(), bytes.as_slice());
    }

    #[test]
    fn test_from_bytes_accepts_secret_at_minimum_length() {
        let secret = HighEntropySecret::from_internal(vec![1u8; MIN_SECRET_LENGTH].as_slice());
        assert_eq!(secret.as_bytes().expose_owned().len(), MIN_SECRET_LENGTH);
    }

    #[test]
    fn test_clone_preserves_secret_bytes() {
        let secret = HighEntropySecret::make(32).unwrap();
        let cloned = secret.clone();
        assert_eq!(
            secret.as_bytes().expose_owned(),
            cloned.as_bytes().expose_owned()
        );
    }
}
