[bindings.kotlin]
package_name = "com.bitwarden.pm"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "BitwardenPMFFI"
module_name = "BitwardenPM"
generate_immutable_records = true
