[package]
name = "memory-testing"
version = "0.1.0"
publish = false

authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[dependencies]
bitwarden-crypto = { workspace = true }
comfy-table = "7.1.1"
hex = "0.4.3"
serde = "1.0.196"
serde_json = "1.0.113"
zeroize = { version = "1.7.0", features = ["serde"] }
