[package]
name = "bitwarden-access-token"
description = """
Internal crate for the bitwarden crate. Do not use.
"""

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license = "GPL-3.0-only OR LicenseRef-Bitwarden-SDK"
keywords.workspace = true

[dependencies]
bitwarden-access-token-crypto = { workspace = true }
bitwarden-crypto = { workspace = true }
bitwarden-encoding = { workspace = true }
bitwarden-sensitive-value = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
