/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccessRequestDetailsResponseModel : An access request with its denormalized requester identity, serving the approver inbox, the caller's own request list, and the cipher access-state snapshot. Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.ExpiredAt has no backing store in v1 and is always null; Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.RuleId is the rule pinned at submit (null for requests created before pinning existed).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessRequestDetailsResponseModel {
    #[serde(rename = "object", alias = "Object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The access request's unique identifier.
    #[serde(rename = "id", alias = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The cipher access was requested for.
    #[serde(rename = "cipherId", alias = "CipherId", skip_serializing_if = "Option::is_none")]
    pub cipher_id: Option<uuid::Uuid>,
    /// The collection the cipher belongs to, through which the request is governed.
    #[serde(rename = "collectionId", alias = "CollectionId", skip_serializing_if = "Option::is_none")]
    pub collection_id: Option<uuid::Uuid>,
    /// The organization that owns the cipher.
    #[serde(rename = "organizationId", alias = "OrganizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<uuid::Uuid>,
    /// The member who opened the request.
    #[serde(rename = "requesterId", alias = "RequesterId", skip_serializing_if = "Option::is_none")]
    pub requester_id: Option<uuid::Uuid>,
    /// The access rule that gated the cipher and that this request is evaluated against, resolved once at submit (oldest wins) and pinned on the request. Null for requests created before pinning existed.
    #[serde(rename = "ruleId", alias = "RuleId", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<uuid::Uuid>,
    #[serde(rename = "status", alias = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::AccessRequestStatus>,
    /// The activation window resolved at submit — the bounds on WHEN this request may be promoted to a lease. Both scheduled and immediate requests are normalized into this window at submit (an immediate request gets a concrete start/end), so there is no separate duration or mode field; the length is Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.LeaseNotAfter minus Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.LeaseNotBefore. In v1 the approved and leased windows are identical to this one.
    #[serde(rename = "leaseNotBefore", alias = "LeaseNotBefore", skip_serializing_if = "Option::is_none")]
    pub lease_not_before: Option<String>,
    /// The end of the resolved activation window (UTC); see Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.LeaseNotBefore.
    #[serde(rename = "leaseNotAfter", alias = "LeaseNotAfter", skip_serializing_if = "Option::is_none")]
    pub lease_not_after: Option<String>,
    /// The optional justification the requester supplied when opening the request.
    #[serde(rename = "reason", alias = "Reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// When the request was opened (UTC).
    #[serde(rename = "submittedAt", alias = "SubmittedAt", skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<String>,
    /// When the request was approved, denied, or cancelled (UTC); null while pending.
    #[serde(rename = "resolvedAt", alias = "ResolvedAt", skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<String>,
    /// Distinct from Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.ResolvedAt; set when an approved request lapses unactivated. Not tracked in v1.
    #[serde(rename = "expiredAt", alias = "ExpiredAt", skip_serializing_if = "Option::is_none")]
    pub expired_at: Option<String>,
    /// The request's decision log, oldest first — one element per decision (human or automatic). Each carries who decided (`deciderKind`), the verdict, and (for a human decision) the approver's identity and comment. Empty only while pending. An array so multi-party approval lands without breaking the contract.
    #[serde(rename = "decisions", alias = "Decisions", skip_serializing_if = "Option::is_none")]
    pub decisions: Option<Vec<models::AccessRequestDecisionResponseModel>>,
    /// Set once an approved request has produced a lease.
    #[serde(rename = "producedLeaseId", alias = "ProducedLeaseId", skip_serializing_if = "Option::is_none")]
    pub produced_lease_id: Option<uuid::Uuid>,
    #[serde(rename = "producedLeaseStatus", alias = "ProducedLeaseStatus", skip_serializing_if = "Option::is_none")]
    pub produced_lease_status: Option<models::AccessLeaseStatus>,
    /// The parent lease if this is an extension request.
    #[serde(rename = "extensionOfLeaseId", alias = "ExtensionOfLeaseId", skip_serializing_if = "Option::is_none")]
    pub extension_of_lease_id: Option<uuid::Uuid>,
    /// The requester's display name, denormalized by the server; null only when the user could not be resolved.
    #[serde(rename = "requesterName", alias = "RequesterName", skip_serializing_if = "Option::is_none")]
    pub requester_name: Option<String>,
    /// The requester's email, denormalized by the server; null only when the user could not be resolved.
    #[serde(rename = "requesterEmail", alias = "RequesterEmail", skip_serializing_if = "Option::is_none")]
    pub requester_email: Option<String>,
}

impl AccessRequestDetailsResponseModel {
    /// An access request with its denormalized requester identity, serving the approver inbox, the caller's own request list, and the cipher access-state snapshot. Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.ExpiredAt has no backing store in v1 and is always null; Bit.Services.Pam.Api.Models.Response.AccessRequestDetailsResponseModel.RuleId is the rule pinned at submit (null for requests created before pinning existed).
    pub fn new() -> AccessRequestDetailsResponseModel {
        AccessRequestDetailsResponseModel {
            object: None,
            id: None,
            cipher_id: None,
            collection_id: None,
            organization_id: None,
            requester_id: None,
            rule_id: None,
            status: None,
            lease_not_before: None,
            lease_not_after: None,
            reason: None,
            submitted_at: None,
            resolved_at: None,
            expired_at: None,
            decisions: None,
            produced_lease_id: None,
            produced_lease_status: None,
            extension_of_lease_id: None,
            requester_name: None,
            requester_email: None,
        }
    }
}

