/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingAddressSelections {
    #[serde(
        rename = "country",
        alias = "Country",
        skip_serializing_if = "Option::is_none"
    )]
    pub country: Option<String>,
    #[serde(
        rename = "postalCode",
        alias = "PostalCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    #[serde(
        rename = "taxId",
        alias = "TaxId",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_id: Option<Box<models::TaxIdSelection>>,
}

impl BillingAddressSelections {
    pub fn new() -> BillingAddressSelections {
        BillingAddressSelections {
            country: None,
            postal_code: None,
            tax_id: None,
        }
    }
}
