/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// ClaimableRotationJobResponseModel : A single claimable rotation job, as a daemon's poll (`GET
/// rotation/daemon/jobs`) sees it -- the candidate set spec `ClaimRotation` claims from.
/// Bit.Services.Pam.Rotation.Api.Models.Response.ClaimableRotationJobResponseModel.TargetSystemId
/// is resolved from the job's config, since the job row itself does not carry it (only
/// `RotationConfigId`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimableRotationJobResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    #[serde(
        rename = "jobId",
        alias = "JobId",
        skip_serializing_if = "Option::is_none"
    )]
    pub job_id: Option<uuid::Uuid>,
    #[serde(
        rename = "source",
        alias = "Source",
        skip_serializing_if = "Option::is_none"
    )]
    pub source: Option<models::PamRotationSource>,
    #[serde(
        rename = "nextClaimableAt",
        alias = "NextClaimableAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_claimable_at: Option<String>,
    #[serde(
        rename = "expiresAt",
        alias = "ExpiresAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<String>,
    #[serde(
        rename = "targetSystemId",
        alias = "TargetSystemId",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_system_id: Option<uuid::Uuid>,
}

impl ClaimableRotationJobResponseModel {
    /// A single claimable rotation job, as a daemon's poll (`GET rotation/daemon/jobs`) sees it --
    /// the candidate set spec `ClaimRotation` claims from.
    /// Bit.Services.Pam.Rotation.Api.Models.Response.ClaimableRotationJobResponseModel.
    /// TargetSystemId is resolved from the job's config, since the job row itself does not carry it
    /// (only `RotationConfigId`).
    pub fn new() -> ClaimableRotationJobResponseModel {
        ClaimableRotationJobResponseModel {
            object: None,
            job_id: None,
            source: None,
            next_claimable_at: None,
            expires_at: None,
            target_system_id: None,
        }
    }
}
