/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Visitor};

use crate::models;
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum ClientType {
    All,
    Web,
    Browser,
    Desktop,
    Mobile,
    Cli,

    /// Unknown value returned from the server. This is used to handle forward compatibility.
    __Unknown(i64),
}

impl ClientType {
    pub fn as_i64(&self) -> i64 {
        match self {
            Self::All => 0,
            Self::Web => 1,
            Self::Browser => 2,
            Self::Desktop => 3,
            Self::Mobile => 4,
            Self::Cli => 5,
            Self::__Unknown(v) => *v,
        }
    }

    pub fn from_i64(value: i64) -> Self {
        match value {
            0 => Self::All,
            1 => Self::Web,
            2 => Self::Browser,
            3 => Self::Desktop,
            4 => Self::Mobile,
            5 => Self::Cli,
            v => Self::__Unknown(v),
        }
    }
}

impl serde::Serialize for ClientType {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_i64(self.as_i64())
    }
}

impl<'de> serde::Deserialize<'de> for ClientType {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct ClientTypeVisitor;

        impl Visitor<'_> for ClientTypeVisitor {
            type Value = ClientType;

            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("an integer")
            }

            fn visit_i64<E: serde::de::Error>(self, v: i64) -> Result<Self::Value, E> {
                Ok(ClientType::from_i64(v))
            }

            fn visit_u64<E: serde::de::Error>(self, v: u64) -> Result<Self::Value, E> {
                Ok(ClientType::from_i64(v as i64))
            }
        }

        deserializer.deserialize_i64(ClientTypeVisitor)
    }
}

impl std::fmt::Display for ClientType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_i64())
    }
}
impl Default for ClientType {
    fn default() -> ClientType {
        Self::All
    }
}
