/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCollectionRequestModel {
    #[serde(rename = "name", alias = "Name")]
    pub name: String,
    #[serde(
        rename = "externalId",
        alias = "ExternalId",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_id: Option<String>,
    #[serde(
        rename = "groups",
        alias = "Groups",
        skip_serializing_if = "Option::is_none"
    )]
    pub groups: Option<Vec<models::SelectionReadOnlyRequestModel>>,
    #[serde(
        rename = "users",
        alias = "Users",
        skip_serializing_if = "Option::is_none"
    )]
    pub users: Option<Vec<models::SelectionReadOnlyRequestModel>>,
}

impl CreateCollectionRequestModel {
    pub fn new(name: String) -> CreateCollectionRequestModel {
        CreateCollectionRequestModel {
            name,
            external_id: None,
            groups: None,
            users: None,
        }
    }
}
