/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmergencyAccessGranteeDetailsResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    #[serde(rename = "id", alias = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(
        rename = "status",
        alias = "Status",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<models::EmergencyAccessStatusType>,
    #[serde(
        rename = "type",
        alias = "R#type",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#type: Option<models::EmergencyAccessType>,
    #[serde(
        rename = "waitTimeDays",
        alias = "WaitTimeDays",
        skip_serializing_if = "Option::is_none"
    )]
    pub wait_time_days: Option<i32>,
    #[serde(
        rename = "granteeId",
        alias = "GranteeId",
        skip_serializing_if = "Option::is_none"
    )]
    pub grantee_id: Option<uuid::Uuid>,
    #[serde(
        rename = "name",
        alias = "Name",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<String>,
    #[serde(
        rename = "email",
        alias = "Email",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<String>,
    #[serde(
        rename = "avatarColor",
        alias = "AvatarColor",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar_color: Option<String>,
}

impl EmergencyAccessGranteeDetailsResponseModel {
    pub fn new() -> EmergencyAccessGranteeDetailsResponseModel {
        EmergencyAccessGranteeDetailsResponseModel {
            object: None,
            id: None,
            status: None,
            r#type: None,
            wait_time_days: None,
            grantee_id: None,
            name: None,
            email: None,
            avatar_color: None,
        }
    }
}
