/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    #[serde(
        rename = "message",
        alias = "Message",
        skip_serializing_if = "Option::is_none"
    )]
    pub message: Option<String>,
    #[serde(
        rename = "validationErrors",
        alias = "ValidationErrors",
        skip_serializing_if = "Option::is_none"
    )]
    pub validation_errors: Option<std::collections::HashMap<String, Vec<String>>>,
    #[serde(
        rename = "exceptionMessage",
        alias = "ExceptionMessage",
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_message: Option<String>,
    #[serde(
        rename = "exceptionStackTrace",
        alias = "ExceptionStackTrace",
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_stack_trace: Option<String>,
    #[serde(
        rename = "innerExceptionMessage",
        alias = "InnerExceptionMessage",
        skip_serializing_if = "Option::is_none"
    )]
    pub inner_exception_message: Option<String>,
}

impl ErrorResponseModel {
    pub fn new() -> ErrorResponseModel {
        ErrorResponseModel {
            object: None,
            message: None,
            validation_errors: None,
            exception_message: None,
            exception_stack_trace: None,
            inner_exception_message: None,
        }
    }
}
