/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationInviteLinkPoliciesRequestModel {
    #[serde(rename = "organizationId", alias = "OrganizationId")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "code", alias = "Code")]
    pub code: uuid::Uuid,
}

impl GetOrganizationInviteLinkPoliciesRequestModel {
    pub fn new(
        organization_id: uuid::Uuid,
        code: uuid::Uuid,
    ) -> GetOrganizationInviteLinkPoliciesRequestModel {
        GetOrganizationInviteLinkPoliciesRequestModel {
            organization_id,
            code,
        }
    }
}
