/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantedProjectAccessPolicyResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    #[serde(
        rename = "read",
        alias = "Read",
        skip_serializing_if = "Option::is_none"
    )]
    pub read: Option<bool>,
    #[serde(
        rename = "write",
        alias = "Write",
        skip_serializing_if = "Option::is_none"
    )]
    pub write: Option<bool>,
    #[serde(
        rename = "grantedProjectId",
        alias = "GrantedProjectId",
        skip_serializing_if = "Option::is_none"
    )]
    pub granted_project_id: Option<uuid::Uuid>,
    #[serde(
        rename = "grantedProjectName",
        alias = "GrantedProjectName",
        skip_serializing_if = "Option::is_none"
    )]
    pub granted_project_name: Option<String>,
}

impl GrantedProjectAccessPolicyResponseModel {
    pub fn new() -> GrantedProjectAccessPolicyResponseModel {
        GrantedProjectAccessPolicyResponseModel {
            object: None,
            read: None,
            write: None,
            granted_project_id: None,
            granted_project_name: None,
        }
    }
}
