/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MasterPasswordAuthenticationDataRequestModel {
    #[serde(rename = "kdf", alias = "Kdf")]
    pub kdf: Box<models::KdfRequestModel>,
    #[serde(
        rename = "masterPasswordAuthenticationHash",
        alias = "MasterPasswordAuthenticationHash"
    )]
    pub master_password_authentication_hash: Option<String>,
    #[serde(rename = "salt", alias = "Salt")]
    pub salt: Option<String>,
}

impl MasterPasswordAuthenticationDataRequestModel {
    pub fn new(
        kdf: models::KdfRequestModel,
        master_password_authentication_hash: Option<String>,
        salt: Option<String>,
    ) -> MasterPasswordAuthenticationDataRequestModel {
        MasterPasswordAuthenticationDataRequestModel {
            kdf: Box::new(kdf),
            master_password_authentication_hash,
            salt,
        }
    }
}
