/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinimalTokenizedPaymentMethodRequest {
    #[serde(rename = "type", alias = "R#type")]
    pub r#type: String,
    #[serde(rename = "token", alias = "Token")]
    pub token: String,
}

impl MinimalTokenizedPaymentMethodRequest {
    pub fn new(r#type: String, token: String) -> MinimalTokenizedPaymentMethodRequest {
        MinimalTokenizedPaymentMethodRequest { r#type, token }
    }
}
