/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationPrivateKeyResponseModel {
    #[serde(
        rename = "object",
        alias = "Object",
        skip_serializing_if = "Option::is_none"
    )]
    pub object: Option<String>,
    #[serde(
        rename = "privateKey",
        alias = "PrivateKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub private_key: Option<String>,
}

impl OrganizationPrivateKeyResponseModel {
    pub fn new() -> OrganizationPrivateKeyResponseModel {
        OrganizationPrivateKeyResponseModel {
            object: None,
            private_key: None,
        }
    }
}
