/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Visitor};

use crate::models;
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum OrganizationApiKeyType {
    Default,
    BillingSync,
    Scim,

    /// Unknown value returned from the server. This is used to handle forward compatibility.
    __Unknown(i64),
}

impl OrganizationApiKeyType {
    pub fn as_i64(&self) -> i64 {
        match self {
            Self::Default => 0,
            Self::BillingSync => 1,
            Self::Scim => 2,
            Self::__Unknown(v) => *v,
        }
    }

    pub fn from_i64(value: i64) -> Self {
        match value {
            0 => Self::Default,
            1 => Self::BillingSync,
            2 => Self::Scim,
            v => Self::__Unknown(v),
        }
    }
}

impl serde::Serialize for OrganizationApiKeyType {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_i64(self.as_i64())
    }
}

impl<'de> serde::Deserialize<'de> for OrganizationApiKeyType {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct OrganizationApiKeyTypeVisitor;

        impl Visitor<'_> for OrganizationApiKeyTypeVisitor {
            type Value = OrganizationApiKeyType;

            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("an integer")
            }

            fn visit_i64<E: serde::de::Error>(self, v: i64) -> Result<Self::Value, E> {
                Ok(OrganizationApiKeyType::from_i64(v))
            }

            fn visit_u64<E: serde::de::Error>(self, v: u64) -> Result<Self::Value, E> {
                Ok(OrganizationApiKeyType::from_i64(v as i64))
            }
        }

        deserializer.deserialize_i64(OrganizationApiKeyTypeVisitor)
    }
}

impl std::fmt::Display for OrganizationApiKeyType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_i64())
    }
}
impl Default for OrganizationApiKeyType {
    fn default() -> OrganizationApiKeyType {
        Self::Default
    }
}
