/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// PamRotationAttemptResponseModel : One access connector's try at executing a rotation job. An
/// element of
/// Bit.Services.Pam.AccessConnector.Rotation.Api.Models.Response.PamRotationJobResponseModel.
/// Attempts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PamRotationAttemptResponseModel {
    /// The attempt's unique identifier.
    #[serde(rename = "id", alias = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The rotation job this attempt was made against.
    #[serde(
        rename = "jobId",
        alias = "JobId",
        skip_serializing_if = "Option::is_none"
    )]
    pub job_id: Option<uuid::Uuid>,
    /// The access connector that executed this attempt, fixed for the attempt's lifetime.
    #[serde(
        rename = "claimedByAccessConnectorId",
        alias = "ClaimedByAccessConnectorId",
        skip_serializing_if = "Option::is_none"
    )]
    pub claimed_by_access_connector_id: Option<uuid::Uuid>,
    /// Whether the access connector wrote the rotated secret back to the cipher.
    #[serde(
        rename = "cipherUpdated",
        alias = "CipherUpdated",
        skip_serializing_if = "Option::is_none"
    )]
    pub cipher_updated: Option<bool>,
    #[serde(
        rename = "status",
        alias = "Status",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<models::PamRotationAttemptStatus>,
    /// Why the attempt failed -- the access connector's error code and its optional detail,
    /// combined. Null unless
    /// Bit.Services.Pam.AccessConnector.Rotation.Api.Models.Response.
    /// PamRotationAttemptResponseModel.Status is Bit.Pam.Enums.PamRotationAttemptStatus.Errored.
    #[serde(
        rename = "failureReason",
        alias = "FailureReason",
        skip_serializing_if = "Option::is_none"
    )]
    pub failure_reason: Option<String>,
    #[serde(
        rename = "syncState",
        alias = "SyncState",
        skip_serializing_if = "Option::is_none"
    )]
    pub sync_state: Option<models::PamRotationSyncState>,
    #[serde(
        rename = "sessionTermination",
        alias = "SessionTermination",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_termination: Option<models::PamSessionTerminationOutcome>,
    /// When the attempt was created, at claim time (UTC).
    #[serde(
        rename = "creationDate",
        alias = "CreationDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub creation_date: Option<String>,
    /// When the attempt reached a terminal status (UTC). Null while it is still executing.
    #[serde(
        rename = "resolvedDate",
        alias = "ResolvedDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub resolved_date: Option<String>,
}

impl PamRotationAttemptResponseModel {
    /// One access connector's try at executing a rotation job. An element of
    /// Bit.Services.Pam.AccessConnector.Rotation.Api.Models.Response.PamRotationJobResponseModel.
    /// Attempts.
    pub fn new() -> PamRotationAttemptResponseModel {
        PamRotationAttemptResponseModel {
            id: None,
            job_id: None,
            claimed_by_access_connector_id: None,
            cipher_updated: None,
            status: None,
            failure_reason: None,
            sync_state: None,
            session_termination: None,
            creation_date: None,
            resolved_date: None,
        }
    }
}
