/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct PreviewOrganizationInvoiceRequestBody {
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<uuid::Uuid>,
    #[serde(rename = "passwordManager")]
    pub password_manager: models::OrganizationPasswordManagerRequestModel,
    #[serde(rename = "secretsManager", skip_serializing_if = "Option::is_none")]
    pub secrets_manager: Option<models::SecretsManagerRequestModel>,
    #[serde(rename = "taxInformation")]
    pub tax_information: models::TaxInformationRequestModel,
}

impl PreviewOrganizationInvoiceRequestBody {
    pub fn new(
        password_manager: models::OrganizationPasswordManagerRequestModel,
        tax_information: models::TaxInformationRequestModel,
    ) -> PreviewOrganizationInvoiceRequestBody {
        PreviewOrganizationInvoiceRequestBody {
            organization_id: None,
            password_manager,
            secrets_manager: None,
            tax_information,
        }
    }
}
