/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// RegisterAccessConnectorRequestModel : Registers a new access connector (spec
/// `ConnectorRegistration`).
/// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.
/// EncryptedPayload and
/// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.Key
/// carry the organization key wrapped client-side, so the server holds ciphertext only and never
/// sees the plaintext key.
/// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.Name is
/// a plaintext display label.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterAccessConnectorRequestModel {
    /// The access connector's plaintext display label, shown wherever access connectors are listed
    /// and             managed.
    #[serde(rename = "name", alias = "Name")]
    pub name: String,
    /// The organization key, wrapped client-side with the encryption-key half of the access
    /// connector's credential. Stored verbatim and handed back on every token response so the
    /// access connector can unwrap it locally; the server only ever holds the ciphertext.
    #[serde(rename = "encryptedPayload", alias = "EncryptedPayload")]
    pub encrypted_payload: String,
    /// The key protecting
    /// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.
    /// EncryptedPayload, itself uploaded wrapped -- opaque ciphertext the server stores but can
    /// never use, recoverable only client-side.
    #[serde(rename = "key", alias = "Key")]
    pub key: String,
}

impl RegisterAccessConnectorRequestModel {
    /// Registers a new access connector (spec `ConnectorRegistration`).
    /// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.
    /// EncryptedPayload and
    /// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.Key
    /// carry the organization key wrapped client-side, so the server holds ciphertext only and
    /// never sees the plaintext key.
    /// Bit.Services.Pam.AccessConnector.Api.Models.Request.RegisterAccessConnectorRequestModel.Name
    /// is a plaintext display label.
    pub fn new(
        name: String,
        encrypted_payload: String,
        key: String,
    ) -> RegisterAccessConnectorRequestModel {
        RegisterAccessConnectorRequestModel {
            name,
            encrypted_payload,
            key,
        }
    }
}
