/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetInitialPasswordRequestModel {
    #[serde(
        rename = "masterPasswordHash",
        alias = "MasterPasswordHash",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_password_hash: Option<String>,
    #[serde(rename = "key", alias = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(
        rename = "keys",
        alias = "Keys",
        skip_serializing_if = "Option::is_none"
    )]
    pub keys: Option<Box<models::KeysRequestModel>>,
    #[serde(rename = "kdf", alias = "Kdf", skip_serializing_if = "Option::is_none")]
    pub kdf: Option<models::KdfType>,
    #[serde(
        rename = "kdfIterations",
        alias = "KdfIterations",
        skip_serializing_if = "Option::is_none"
    )]
    pub kdf_iterations: Option<i32>,
    #[serde(
        rename = "kdfMemory",
        alias = "KdfMemory",
        skip_serializing_if = "Option::is_none"
    )]
    pub kdf_memory: Option<i32>,
    #[serde(
        rename = "kdfParallelism",
        alias = "KdfParallelism",
        skip_serializing_if = "Option::is_none"
    )]
    pub kdf_parallelism: Option<i32>,
    #[serde(
        rename = "masterPasswordAuthentication",
        alias = "MasterPasswordAuthentication",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_password_authentication:
        Option<Box<models::MasterPasswordAuthenticationDataRequestModel>>,
    #[serde(
        rename = "masterPasswordUnlock",
        alias = "MasterPasswordUnlock",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_password_unlock: Option<Box<models::MasterPasswordUnlockDataRequestModel>>,
    #[serde(
        rename = "accountKeys",
        alias = "AccountKeys",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_keys: Option<Box<models::AccountKeysRequestModel>>,
    #[serde(
        rename = "masterPasswordHint",
        alias = "MasterPasswordHint",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_password_hint: Option<String>,
    #[serde(rename = "orgIdentifier", alias = "OrgIdentifier")]
    pub org_identifier: String,
}

impl SetInitialPasswordRequestModel {
    pub fn new(org_identifier: String) -> SetInitialPasswordRequestModel {
        SetInitialPasswordRequestModel {
            master_password_hash: None,
            key: None,
            keys: None,
            kdf: None,
            kdf_iterations: None,
            kdf_memory: None,
            kdf_parallelism: None,
            master_password_authentication: None,
            master_password_unlock: None,
            account_keys: None,
            master_password_hint: None,
            org_identifier,
        }
    }
}
