/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// StorageUpdateRequest : Request model for updating storage allocation on a user's premium
/// subscription. Allows for both increasing and decreasing storage in an idempotent manner.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageUpdateRequest {
    /// The additional storage in GB beyond the base storage. Must be between 0 and the maximum
    /// allowed (minus base storage).
    #[serde(rename = "additionalStorageGb", alias = "AdditionalStorageGb")]
    pub additional_storage_gb: i32,
}

impl StorageUpdateRequest {
    /// Request model for updating storage allocation on a user's premium subscription. Allows for
    /// both increasing and decreasing storage in an idempotent manner.
    pub fn new(additional_storage_gb: i32) -> StorageUpdateRequest {
        StorageUpdateRequest {
            additional_storage_gb,
        }
    }
}
