/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// TwoFactorEmailUpdateRequestModel : Request body for the authenticated setup endpoint that
/// completes Email 2FA enrollment by replaying the OTP from the previous setup step. Authenticated
/// by the same user-verification token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorEmailUpdateRequestModel {
    #[serde(rename = "email", alias = "Email")]
    pub email: String,
    /// User-verification token bound to `UserId + ProviderType`. Minted by the matching GET
    /// endpoint and replayed on subsequent management calls so the user does not have to
    /// re-verify.
    #[serde(rename = "userVerificationToken", alias = "UserVerificationToken")]
    pub user_verification_token: String,
    #[serde(rename = "token", alias = "Token")]
    pub token: String,
}

impl TwoFactorEmailUpdateRequestModel {
    /// Request body for the authenticated setup endpoint that completes Email 2FA enrollment by
    /// replaying the OTP from the previous setup step. Authenticated by the same user-verification
    /// token.
    pub fn new(
        email: String,
        user_verification_token: String,
        token: String,
    ) -> TwoFactorEmailUpdateRequestModel {
        TwoFactorEmailUpdateRequestModel {
            email,
            user_verification_token,
            token,
        }
    }
}
