/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// TwoFactorYubiKeyDeleteRequestModel : Request model for deleting a user's YubiKey two-factor
/// configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorYubiKeyDeleteRequestModel {
    /// User-verification token bound to `UserId + ProviderType`. Minted by the matching GET
    /// endpoint and replayed on subsequent management calls so the user does not have to
    /// re-verify.
    #[serde(rename = "userVerificationToken", alias = "UserVerificationToken")]
    pub user_verification_token: String,
}

impl TwoFactorYubiKeyDeleteRequestModel {
    /// Request model for deleting a user's YubiKey two-factor configuration.
    pub fn new(user_verification_token: String) -> TwoFactorYubiKeyDeleteRequestModel {
        TwoFactorYubiKeyDeleteRequestModel {
            user_verification_token,
        }
    }
}
