/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// TwoFactorAuthenticatorDetails : Authenticator provider details. Hydrated from
/// Bit.Core.Entities.User; embedded by the per-action `TwoFactorAuthenticator*ResponseModel`
/// wrappers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorAuthenticatorDetails {
    #[serde(
        rename = "enabled",
        alias = "Enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub enabled: Option<bool>,
    #[serde(rename = "key", alias = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl TwoFactorAuthenticatorDetails {
    /// Authenticator provider details. Hydrated from Bit.Core.Entities.User; embedded by the
    /// per-action `TwoFactorAuthenticator*ResponseModel` wrappers.
    pub fn new() -> TwoFactorAuthenticatorDetails {
        TwoFactorAuthenticatorDetails {
            enabled: None,
            key: None,
        }
    }
}
