/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// TwoFactorEmailDetails : Email provider details. Hydrated from Bit.Core.Entities.User; embedded
/// by the per-action `TwoFactorEmail*ResponseModel` wrappers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorEmailDetails {
    #[serde(
        rename = "enabled",
        alias = "Enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub enabled: Option<bool>,
    #[serde(
        rename = "email",
        alias = "Email",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<String>,
}

impl TwoFactorEmailDetails {
    /// Email provider details. Hydrated from Bit.Core.Entities.User; embedded by the per-action
    /// `TwoFactorEmail*ResponseModel` wrappers.
    pub fn new() -> TwoFactorEmailDetails {
        TwoFactorEmailDetails {
            enabled: None,
            email: None,
        }
    }
}
