/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTempPasswordRequestModel {
    #[serde(rename = "newMasterPasswordHash", alias = "NewMasterPasswordHash", skip_serializing_if = "Option::is_none")]
    pub new_master_password_hash: Option<String>,
    #[serde(rename = "key", alias = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "masterPasswordHint", alias = "MasterPasswordHint", skip_serializing_if = "Option::is_none")]
    pub master_password_hint: Option<String>,
    #[serde(rename = "unlockData", alias = "UnlockData", skip_serializing_if = "Option::is_none")]
    pub unlock_data: Option<Box<models::MasterPasswordUnlockDataRequestModel>>,
    #[serde(rename = "authenticationData", alias = "AuthenticationData", skip_serializing_if = "Option::is_none")]
    pub authentication_data: Option<Box<models::MasterPasswordAuthenticationDataRequestModel>>,
}

impl UpdateTempPasswordRequestModel {
    pub fn new() -> UpdateTempPasswordRequestModel {
        UpdateTempPasswordRequestModel {
            new_master_password_hash: None,
            key: None,
            master_password_hint: None,
            unlock_data: None,
            authentication_data: None,
        }
    }
}

