[bindings.kotlin]
package_name = "com.bitwarden.collections"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "BitwardenCollectionsFFI"
module_name = "BitwardenCollections"
generate_immutable_records = true
