[bindings.kotlin]
package_name = "com.bitwarden.state"
generate_immutable_records = true
android = true
# Temporary workaround for https://github.com/mozilla/uniffi-rs/issues/2740
omit_checksums = true

[bindings.swift]
ffi_module_name = "BitwardenStateFFI"
module_name = "BitwardenState"
generate_immutable_records = true
