[bindings.kotlin]
package_name = "com.bitwarden.sdk"
cdylib_name = "bitwarden_uniffi"
generate_immutable_records = true
android = true
# Temporary workaround for https://github.com/mozilla/uniffi-rs/issues/2740
omit_checksums = true

[bindings.swift]
ffi_module_name = "BitwardenFFI"
module_name = "BitwardenSDK"
generate_immutable_records = true
