/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationExtensionsClientInputs {
    #[serde(
        rename = "example.extension.bool",
        alias = "ExampleExtensionBool",
        skip_serializing_if = "Option::is_none"
    )]
    pub example_extension_bool: Option<bool>,
    #[serde(
        rename = "exts",
        alias = "Exts",
        skip_serializing_if = "Option::is_none"
    )]
    pub exts: Option<bool>,
    #[serde(rename = "uvm", alias = "Uvm", skip_serializing_if = "Option::is_none")]
    pub uvm: Option<bool>,
    #[serde(
        rename = "credProps",
        alias = "CredProps",
        skip_serializing_if = "Option::is_none"
    )]
    pub cred_props: Option<bool>,
    #[serde(rename = "prf", alias = "Prf", skip_serializing_if = "Option::is_none")]
    pub prf: Option<Box<models::AuthenticationExtensionsPrfInputs>>,
    #[serde(
        rename = "largeBlob",
        alias = "LargeBlob",
        skip_serializing_if = "Option::is_none"
    )]
    pub large_blob: Option<Box<models::AuthenticationExtensionsLargeBlobInputs>>,
    #[serde(
        rename = "credentialProtectionPolicy",
        alias = "CredentialProtectionPolicy",
        skip_serializing_if = "Option::is_none"
    )]
    pub credential_protection_policy: Option<models::CredentialProtectionPolicy>,
    #[serde(
        rename = "enforceCredentialProtectionPolicy",
        alias = "EnforceCredentialProtectionPolicy",
        skip_serializing_if = "Option::is_none"
    )]
    pub enforce_credential_protection_policy: Option<bool>,
}

impl AuthenticationExtensionsClientInputs {
    pub fn new() -> AuthenticationExtensionsClientInputs {
        AuthenticationExtensionsClientInputs {
            example_extension_bool: None,
            exts: None,
            uvm: None,
            cred_props: None,
            prf: None,
            large_blob: None,
            credential_protection_policy: None,
            enforce_credential_protection_policy: None,
        }
    }
}
