[package]
name = "bitwarden-core"
description = """
Internal crate for the bitwarden crate. Do not use.
"""

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[features]
internal = ["dep:zxcvbn"]
no-memory-hardening = [
    "bitwarden-crypto/no-memory-hardening"
] # Disable memory hardening features
secrets = [] # Secrets manager API
uniffi = [
    "internal",
    "bitwarden-crypto/uniffi",
    "bitwarden-encoding/uniffi",
    "dep:bitwarden-uniffi-error",
    "dep:uniffi"
] # Uniffi bindings
wasm = [
    "bitwarden-crypto/wasm",
    "bitwarden-encoding/wasm",
    "bitwarden-error/wasm",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:tsify"
] # WASM support

[dependencies]
async-trait = { workspace = true }
bitwarden-api-api = { workspace = true }
bitwarden-api-identity = { workspace = true }
bitwarden-crypto = { workspace = true }
bitwarden-encoding = { workspace = true }
bitwarden-error = { workspace = true }
bitwarden-state = { workspace = true }
bitwarden-uniffi-error = { workspace = true, optional = true }
bitwarden-uuid = { workspace = true }
chrono = { workspace = true, features = ["std"] }
# We don't use this directly (it's used by rand), but we need it here to enable WASM support
getrandom = { version = ">=0.2.9, <0.3", features = ["js"] }
http = "1.3.1"
log = { workspace = true }
rand = ">=0.8.5, <0.9"
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-tracing = ">=0.5.8, <0.6"
schemars = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt"] }
tsify = { workspace = true, optional = true }
uniffi = { workspace = true, optional = true, features = ["tokio"] }
uuid = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
zeroize = { version = ">=1.7.0, <2.0", features = ["derive", "aarch64"] }
zxcvbn = { version = ">=3.0.1, <4.0", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
# By default, we use rustls as the TLS stack and rust-platform-verifier to support user-installed root certificates
# The only exception is WASM, as it just uses the browsers/node fetch
reqwest = { workspace = true, features = ["rustls-tls-manual-roots"] }
rustls = { version = "0.23.19", default-features = false }
rustls-platform-verifier = "0.6.0"

[dev-dependencies]
rand_chacha = "0.3.1"
tokio = { workspace = true, features = ["rt"] }
zeroize = { version = ">=1.7.0, <2.0", features = ["derive", "aarch64"] }

[lints]
workspace = true
