[bindings.kotlin]
package_name = "com.bitwarden.policies"
generate_immutable_records = true
android = true
# Temporary workaround for https://github.com/mozilla/uniffi-rs/issues/2740
omit_checksums = true

[bindings.swift]
ffi_module_name = "BitwardenPoliciesFFI"
module_name = "BitwardenPolicies"
generate_immutable_records = true
