name: Lint

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: ${{ matrix.check }}

    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - check: fmt
            needs_rust: true
            needs_nightly: true
          - check: clippy
            needs_rust: true
          - check: sort
            needs_rust: true
            install: cargo install cargo-sort --version 2.0.2 --locked
          - check: udeps
            needs_rust: true
            needs_nightly: true
            install: cargo install cargo-udeps --version 0.1.57 --locked
          - check: dylint
            needs_rust: true
            install: cargo install cargo-dylint dylint-link --version 5.0.0 --locked
          - check: doc
            needs_rust: true
          - check: prettier
            needs_node: true
          - check: dep-ownership
            needs_node: true
          - check: cargo-lock
            needs_rust: true

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set Rust toolchain version
        if: matrix.needs_rust
        id: toolchain
        shell: bash
        run: |
          RUST_TOOLCHAIN="$(grep -oP '^channel.*"(\K.*?)(?=")' rust-toolchain.toml)"
          echo "RUST_TOOLCHAIN=${RUST_TOOLCHAIN}" | tee -a "${GITHUB_OUTPUT}"

      - name: Set Rust nightly toolchain version
        if: matrix.needs_nightly
        id: nightly-toolchain
        shell: bash
        run: |
          RUST_NIGHTLY_TOOLCHAIN="$(grep -oP '^nightly-channel.*"(\K.*?)(?=")' rust-toolchain.toml)"
          echo "RUST_NIGHTLY_TOOLCHAIN=${RUST_NIGHTLY_TOOLCHAIN}" | tee -a "${GITHUB_OUTPUT}"

      - name: Install Rust
        if: matrix.needs_rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: "${{ steps.toolchain.outputs.RUST_TOOLCHAIN }}"
          components: clippy, rustfmt

      - name: Install Rust nightly
        if: matrix.needs_nightly
        env:
          RUST_NIGHTLY_TOOLCHAIN: ${{ steps.nightly-toolchain.outputs.RUST_NIGHTLY_TOOLCHAIN }}
        run: |
          rustup toolchain install "${RUST_NIGHTLY_TOOLCHAIN}"
          rustup component add rustfmt --toolchain "${RUST_NIGHTLY_TOOLCHAIN}"-x86_64-unknown-linux-gnu

      - name: Cache cargo registry
        if: matrix.needs_rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Install per-check cargo tool
        if: matrix.install
        run: ${{ matrix.install }}

      - name: Install clippy-sarif and sarif-fmt
        if: matrix.check == 'clippy'
        run: cargo install clippy-sarif sarif-fmt --locked --git https://github.com/psastras/sarif-rs.git --rev 11c33a53f6ffeaed736856b86fb6b7b09fabdfd8

      - name: Run clippy with SARIF output
        if: matrix.check == 'clippy'
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo clippy --all-features --all-targets --message-format=json |
          clippy-sarif | tee clippy_result.sarif | sarif-fmt

      - name: Upload clippy results to GitHub
        if: matrix.check == 'clippy'
        uses: github/codeql-action/upload-sarif@6bc82e05fd0ea64601dd4b465378bbcf57de0314 # v4.32.1
        with:
          sarif_file: clippy_result.sarif
          sha: ${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.sha || github.sha }}
          ref: ${{ contains(github.event_name, 'pull_request') && format('refs/pull/{0}/head', github.event.pull_request.number) || github.ref }}

      - name: Set up Node
        if: matrix.needs_node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "16"

      - name: NPM setup
        if: matrix.needs_node
        run: npm ci

      - name: Run lint --only ${{ matrix.check }}
        run: ./scripts/lint.sh --only ${{ matrix.check }}
